-- =============================================================================
-- 2026_05_09_mercedes_models_exhaustive.sql
-- INSERT exhaustif Mercedes-Benz : Classes + trims (200-680) + AMG + vintages
-- ON CONFLICT DO NOTHING pour préserver Wikipedia/DBpedia/NHTSA existants
-- =============================================================================

INSERT INTO public.models_canonical (mk, mo, label_full, source) VALUES
  -- =========================================================================
  -- CLASSES MODERNES (modèles parents)
  -- =========================================================================
  ('Mercedes-Benz', 'A-Class', 'Mercedes-Benz A-Class', 'manual_mb'),
  ('Mercedes-Benz', 'A-Klasse', 'Mercedes-Benz A-Klasse', 'manual_mb'),
  ('Mercedes-Benz', 'B-Class', 'Mercedes-Benz B-Class', 'manual_mb'),
  ('Mercedes-Benz', 'B-Klasse', 'Mercedes-Benz B-Klasse', 'manual_mb'),
  ('Mercedes-Benz', 'C-Class', 'Mercedes-Benz C-Class', 'manual_mb'),
  ('Mercedes-Benz', 'C-Klasse', 'Mercedes-Benz C-Klasse', 'manual_mb'),
  ('Mercedes-Benz', 'CLA-Class', 'Mercedes-Benz CLA-Class', 'manual_mb'),
  ('Mercedes-Benz', 'CLC-Class', 'Mercedes-Benz CLC-Class', 'manual_mb'),
  ('Mercedes-Benz', 'CLK-Class', 'Mercedes-Benz CLK-Class', 'manual_mb'),
  ('Mercedes-Benz', 'CLS-Class', 'Mercedes-Benz CLS-Class', 'manual_mb'),
  ('Mercedes-Benz', 'CL-Class', 'Mercedes-Benz CL-Class', 'manual_mb'),
  ('Mercedes-Benz', 'E-Class', 'Mercedes-Benz E-Class', 'manual_mb'),
  ('Mercedes-Benz', 'E-Klasse', 'Mercedes-Benz E-Klasse', 'manual_mb'),
  ('Mercedes-Benz', 'G-Class', 'Mercedes-Benz G-Class', 'manual_mb'),
  ('Mercedes-Benz', 'G-Klasse', 'Mercedes-Benz G-Klasse', 'manual_mb'),
  ('Mercedes-Benz', 'GLA-Class', 'Mercedes-Benz GLA-Class', 'manual_mb'),
  ('Mercedes-Benz', 'GLB-Class', 'Mercedes-Benz GLB-Class', 'manual_mb'),
  ('Mercedes-Benz', 'GLC-Class', 'Mercedes-Benz GLC-Class', 'manual_mb'),
  ('Mercedes-Benz', 'GLE-Class', 'Mercedes-Benz GLE-Class', 'manual_mb'),
  ('Mercedes-Benz', 'GLK-Class', 'Mercedes-Benz GLK-Class', 'manual_mb'),
  ('Mercedes-Benz', 'GL-Class', 'Mercedes-Benz GL-Class', 'manual_mb'),
  ('Mercedes-Benz', 'GLS-Class', 'Mercedes-Benz GLS-Class', 'manual_mb'),
  ('Mercedes-Benz', 'M-Class', 'Mercedes-Benz M-Class', 'manual_mb'),
  ('Mercedes-Benz', 'ML-Class', 'Mercedes-Benz ML-Class', 'manual_mb'),
  ('Mercedes-Benz', 'R-Class', 'Mercedes-Benz R-Class', 'manual_mb'),
  ('Mercedes-Benz', 'S-Class', 'Mercedes-Benz S-Class', 'manual_mb'),
  ('Mercedes-Benz', 'S-Klasse', 'Mercedes-Benz S-Klasse', 'manual_mb'),
  ('Mercedes-Benz', 'SL-Class', 'Mercedes-Benz SL-Class', 'manual_mb'),
  ('Mercedes-Benz', 'SLC-Class', 'Mercedes-Benz SLC-Class', 'manual_mb'),
  ('Mercedes-Benz', 'SLK-Class', 'Mercedes-Benz SLK-Class', 'manual_mb'),
  ('Mercedes-Benz', 'V-Class', 'Mercedes-Benz V-Class', 'manual_mb'),
  ('Mercedes-Benz', 'X-Class', 'Mercedes-Benz X-Class', 'manual_mb'),
  -- EQ électriques
  ('Mercedes-Benz', 'EQA', 'Mercedes-Benz EQA', 'manual_mb'),
  ('Mercedes-Benz', 'EQB', 'Mercedes-Benz EQB', 'manual_mb'),
  ('Mercedes-Benz', 'EQC', 'Mercedes-Benz EQC', 'manual_mb'),
  ('Mercedes-Benz', 'EQE', 'Mercedes-Benz EQE', 'manual_mb'),
  ('Mercedes-Benz', 'EQE SUV', 'Mercedes-Benz EQE SUV', 'manual_mb'),
  ('Mercedes-Benz', 'EQS', 'Mercedes-Benz EQS', 'manual_mb'),
  ('Mercedes-Benz', 'EQS SUV', 'Mercedes-Benz EQS SUV', 'manual_mb'),
  ('Mercedes-Benz', 'EQV', 'Mercedes-Benz EQV', 'manual_mb'),
  -- Vans/Utilitaires (kept: cars commerciales mais vendus particuliers)
  ('Mercedes-Benz', 'Citan', 'Mercedes-Benz Citan', 'manual_mb'),
  ('Mercedes-Benz', 'Vito', 'Mercedes-Benz Vito', 'manual_mb'),
  ('Mercedes-Benz', 'Viano', 'Mercedes-Benz Viano', 'manual_mb'),
  ('Mercedes-Benz', 'Sprinter', 'Mercedes-Benz Sprinter', 'manual_mb'),
  ('Mercedes-Benz', 'Vaneo', 'Mercedes-Benz Vaneo', 'manual_mb'),

  -- =========================================================================
  -- TRIMS A-Class
  -- =========================================================================
  ('Mercedes-Benz', 'A 140', 'Mercedes-Benz A 140', 'manual_mb'),
  ('Mercedes-Benz', 'A 150', 'Mercedes-Benz A 150', 'manual_mb'),
  ('Mercedes-Benz', 'A 160', 'Mercedes-Benz A 160', 'manual_mb'),
  ('Mercedes-Benz', 'A 170', 'Mercedes-Benz A 170', 'manual_mb'),
  ('Mercedes-Benz', 'A 180', 'Mercedes-Benz A 180', 'manual_mb'),
  ('Mercedes-Benz', 'A 200', 'Mercedes-Benz A 200', 'manual_mb'),
  ('Mercedes-Benz', 'A 220', 'Mercedes-Benz A 220', 'manual_mb'),
  ('Mercedes-Benz', 'A 250', 'Mercedes-Benz A 250', 'manual_mb'),
  ('Mercedes-Benz', 'A 35 AMG', 'Mercedes-Benz A 35 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'A 45 AMG', 'Mercedes-Benz A 45 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'A 45 S', 'Mercedes-Benz A 45 S', 'manual_mb'),

  -- =========================================================================
  -- TRIMS B-Class
  -- =========================================================================
  ('Mercedes-Benz', 'B 150', 'Mercedes-Benz B 150', 'manual_mb'),
  ('Mercedes-Benz', 'B 160', 'Mercedes-Benz B 160', 'manual_mb'),
  ('Mercedes-Benz', 'B 170', 'Mercedes-Benz B 170', 'manual_mb'),
  ('Mercedes-Benz', 'B 180', 'Mercedes-Benz B 180', 'manual_mb'),
  ('Mercedes-Benz', 'B 200', 'Mercedes-Benz B 200', 'manual_mb'),
  ('Mercedes-Benz', 'B 220', 'Mercedes-Benz B 220', 'manual_mb'),
  ('Mercedes-Benz', 'B 250', 'Mercedes-Benz B 250', 'manual_mb'),

  -- =========================================================================
  -- TRIMS C-Class
  -- =========================================================================
  ('Mercedes-Benz', 'C 180', 'Mercedes-Benz C 180', 'manual_mb'),
  ('Mercedes-Benz', 'C 200', 'Mercedes-Benz C 200', 'manual_mb'),
  ('Mercedes-Benz', 'C 220', 'Mercedes-Benz C 220', 'manual_mb'),
  ('Mercedes-Benz', 'C 230', 'Mercedes-Benz C 230', 'manual_mb'),
  ('Mercedes-Benz', 'C 240', 'Mercedes-Benz C 240', 'manual_mb'),
  ('Mercedes-Benz', 'C 250', 'Mercedes-Benz C 250', 'manual_mb'),
  ('Mercedes-Benz', 'C 270', 'Mercedes-Benz C 270', 'manual_mb'),
  ('Mercedes-Benz', 'C 280', 'Mercedes-Benz C 280', 'manual_mb'),
  ('Mercedes-Benz', 'C 300', 'Mercedes-Benz C 300', 'manual_mb'),
  ('Mercedes-Benz', 'C 320', 'Mercedes-Benz C 320', 'manual_mb'),
  ('Mercedes-Benz', 'C 350', 'Mercedes-Benz C 350', 'manual_mb'),
  ('Mercedes-Benz', 'C 400', 'Mercedes-Benz C 400', 'manual_mb'),
  ('Mercedes-Benz', 'C 430', 'Mercedes-Benz C 430', 'manual_mb'),
  ('Mercedes-Benz', 'C 450', 'Mercedes-Benz C 450', 'manual_mb'),
  ('Mercedes-Benz', 'C 32 AMG', 'Mercedes-Benz C 32 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'C 36 AMG', 'Mercedes-Benz C 36 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'C 43 AMG', 'Mercedes-Benz C 43 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'C 55 AMG', 'Mercedes-Benz C 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'C 63 AMG', 'Mercedes-Benz C 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'C 63 S', 'Mercedes-Benz C 63 S', 'manual_mb'),

  -- =========================================================================
  -- TRIMS CLA / CLS / CLK / CLC
  -- =========================================================================
  ('Mercedes-Benz', 'CLA 180', 'Mercedes-Benz CLA 180', 'manual_mb'),
  ('Mercedes-Benz', 'CLA 200', 'Mercedes-Benz CLA 200', 'manual_mb'),
  ('Mercedes-Benz', 'CLA 220', 'Mercedes-Benz CLA 220', 'manual_mb'),
  ('Mercedes-Benz', 'CLA 250', 'Mercedes-Benz CLA 250', 'manual_mb'),
  ('Mercedes-Benz', 'CLA 35 AMG', 'Mercedes-Benz CLA 35 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLA 45 AMG', 'Mercedes-Benz CLA 45 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLA 45 S', 'Mercedes-Benz CLA 45 S', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 250', 'Mercedes-Benz CLS 250', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 280', 'Mercedes-Benz CLS 280', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 320', 'Mercedes-Benz CLS 320', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 350', 'Mercedes-Benz CLS 350', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 400', 'Mercedes-Benz CLS 400', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 450', 'Mercedes-Benz CLS 450', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 500', 'Mercedes-Benz CLS 500', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 550', 'Mercedes-Benz CLS 550', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 53 AMG', 'Mercedes-Benz CLS 53 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 55 AMG', 'Mercedes-Benz CLS 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLS 63 AMG', 'Mercedes-Benz CLS 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 200', 'Mercedes-Benz CLK 200', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 230', 'Mercedes-Benz CLK 230', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 240', 'Mercedes-Benz CLK 240', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 270', 'Mercedes-Benz CLK 270', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 280', 'Mercedes-Benz CLK 280', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 320', 'Mercedes-Benz CLK 320', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 350', 'Mercedes-Benz CLK 350', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 430', 'Mercedes-Benz CLK 430', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 500', 'Mercedes-Benz CLK 500', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 55 AMG', 'Mercedes-Benz CLK 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLK 63 AMG', 'Mercedes-Benz CLK 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLK GTR', 'Mercedes-Benz CLK GTR', 'manual_mb'),
  ('Mercedes-Benz', 'CLK DTM AMG', 'Mercedes-Benz CLK DTM AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CLC 180', 'Mercedes-Benz CLC 180', 'manual_mb'),
  ('Mercedes-Benz', 'CLC 200', 'Mercedes-Benz CLC 200', 'manual_mb'),
  ('Mercedes-Benz', 'CLC 220', 'Mercedes-Benz CLC 220', 'manual_mb'),
  ('Mercedes-Benz', 'CLC 350', 'Mercedes-Benz CLC 350', 'manual_mb'),
  ('Mercedes-Benz', 'CL 500', 'Mercedes-Benz CL 500', 'manual_mb'),
  ('Mercedes-Benz', 'CL 550', 'Mercedes-Benz CL 550', 'manual_mb'),
  ('Mercedes-Benz', 'CL 600', 'Mercedes-Benz CL 600', 'manual_mb'),
  ('Mercedes-Benz', 'CL 63 AMG', 'Mercedes-Benz CL 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'CL 65 AMG', 'Mercedes-Benz CL 65 AMG', 'manual_mb'),

  -- =========================================================================
  -- TRIMS E-Class
  -- =========================================================================
  ('Mercedes-Benz', 'E 200', 'Mercedes-Benz E 200', 'manual_mb'),
  ('Mercedes-Benz', 'E 220', 'Mercedes-Benz E 220', 'manual_mb'),
  ('Mercedes-Benz', 'E 230', 'Mercedes-Benz E 230', 'manual_mb'),
  ('Mercedes-Benz', 'E 240', 'Mercedes-Benz E 240', 'manual_mb'),
  ('Mercedes-Benz', 'E 250', 'Mercedes-Benz E 250', 'manual_mb'),
  ('Mercedes-Benz', 'E 270', 'Mercedes-Benz E 270', 'manual_mb'),
  ('Mercedes-Benz', 'E 280', 'Mercedes-Benz E 280', 'manual_mb'),
  ('Mercedes-Benz', 'E 300', 'Mercedes-Benz E 300', 'manual_mb'),
  ('Mercedes-Benz', 'E 320', 'Mercedes-Benz E 320', 'manual_mb'),
  ('Mercedes-Benz', 'E 350', 'Mercedes-Benz E 350', 'manual_mb'),
  ('Mercedes-Benz', 'E 400', 'Mercedes-Benz E 400', 'manual_mb'),
  ('Mercedes-Benz', 'E 420', 'Mercedes-Benz E 420', 'manual_mb'),
  ('Mercedes-Benz', 'E 430', 'Mercedes-Benz E 430', 'manual_mb'),
  ('Mercedes-Benz', 'E 450', 'Mercedes-Benz E 450', 'manual_mb'),
  ('Mercedes-Benz', 'E 500', 'Mercedes-Benz E 500', 'manual_mb'),
  ('Mercedes-Benz', 'E 50 AMG', 'Mercedes-Benz E 50 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'E 53 AMG', 'Mercedes-Benz E 53 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'E 55 AMG', 'Mercedes-Benz E 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'E 60 AMG', 'Mercedes-Benz E 60 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'E 63 AMG', 'Mercedes-Benz E 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'E 63 S', 'Mercedes-Benz E 63 S', 'manual_mb'),

  -- =========================================================================
  -- TRIMS S-Class (incl. Maybach)
  -- =========================================================================
  ('Mercedes-Benz', 'S 280', 'Mercedes-Benz S 280', 'manual_mb'),
  ('Mercedes-Benz', 'S 320', 'Mercedes-Benz S 320', 'manual_mb'),
  ('Mercedes-Benz', 'S 350', 'Mercedes-Benz S 350', 'manual_mb'),
  ('Mercedes-Benz', 'S 400', 'Mercedes-Benz S 400', 'manual_mb'),
  ('Mercedes-Benz', 'S 420', 'Mercedes-Benz S 420', 'manual_mb'),
  ('Mercedes-Benz', 'S 430', 'Mercedes-Benz S 430', 'manual_mb'),
  ('Mercedes-Benz', 'S 450', 'Mercedes-Benz S 450', 'manual_mb'),
  ('Mercedes-Benz', 'S 500', 'Mercedes-Benz S 500', 'manual_mb'),
  ('Mercedes-Benz', 'S 550', 'Mercedes-Benz S 550', 'manual_mb'),
  ('Mercedes-Benz', 'S 560', 'Mercedes-Benz S 560', 'manual_mb'),
  ('Mercedes-Benz', 'S 580', 'Mercedes-Benz S 580', 'manual_mb'),
  ('Mercedes-Benz', 'S 600', 'Mercedes-Benz S 600', 'manual_mb'),
  ('Mercedes-Benz', 'S 650', 'Mercedes-Benz S 650', 'manual_mb'),
  ('Mercedes-Benz', 'S 680', 'Mercedes-Benz S 680', 'manual_mb'),
  ('Mercedes-Benz', 'S 55 AMG', 'Mercedes-Benz S 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'S 63 AMG', 'Mercedes-Benz S 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'S 65 AMG', 'Mercedes-Benz S 65 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'S 600 Maybach', 'Mercedes-Benz S 600 Maybach', 'manual_mb'),
  ('Mercedes-Benz', 'S 600 Pullman', 'Mercedes-Benz S 600 Pullman', 'manual_mb'),
  ('Mercedes-Benz', 'S 650 Maybach', 'Mercedes-Benz S 650 Maybach', 'manual_mb'),
  ('Mercedes-Benz', 'S 680 Maybach', 'Mercedes-Benz S 680 Maybach', 'manual_mb'),

  -- =========================================================================
  -- TRIMS GLA / GLB / GLC / GLE / GLS / G / GL / GLK / M / ML
  -- =========================================================================
  ('Mercedes-Benz', 'GLA 180', 'Mercedes-Benz GLA 180', 'manual_mb'),
  ('Mercedes-Benz', 'GLA 200', 'Mercedes-Benz GLA 200', 'manual_mb'),
  ('Mercedes-Benz', 'GLA 220', 'Mercedes-Benz GLA 220', 'manual_mb'),
  ('Mercedes-Benz', 'GLA 250', 'Mercedes-Benz GLA 250', 'manual_mb'),
  ('Mercedes-Benz', 'GLA 35 AMG', 'Mercedes-Benz GLA 35 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLA 45 AMG', 'Mercedes-Benz GLA 45 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLB 180', 'Mercedes-Benz GLB 180', 'manual_mb'),
  ('Mercedes-Benz', 'GLB 200', 'Mercedes-Benz GLB 200', 'manual_mb'),
  ('Mercedes-Benz', 'GLB 220', 'Mercedes-Benz GLB 220', 'manual_mb'),
  ('Mercedes-Benz', 'GLB 250', 'Mercedes-Benz GLB 250', 'manual_mb'),
  ('Mercedes-Benz', 'GLB 35 AMG', 'Mercedes-Benz GLB 35 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 200', 'Mercedes-Benz GLC 200', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 220', 'Mercedes-Benz GLC 220', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 250', 'Mercedes-Benz GLC 250', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 300', 'Mercedes-Benz GLC 300', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 350', 'Mercedes-Benz GLC 350', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 400', 'Mercedes-Benz GLC 400', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 43 AMG', 'Mercedes-Benz GLC 43 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 63 AMG', 'Mercedes-Benz GLC 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLC 63 S', 'Mercedes-Benz GLC 63 S', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 250', 'Mercedes-Benz GLE 250', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 300', 'Mercedes-Benz GLE 300', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 350', 'Mercedes-Benz GLE 350', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 400', 'Mercedes-Benz GLE 400', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 450', 'Mercedes-Benz GLE 450', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 500', 'Mercedes-Benz GLE 500', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 53 AMG', 'Mercedes-Benz GLE 53 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 63 AMG', 'Mercedes-Benz GLE 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLE 63 S', 'Mercedes-Benz GLE 63 S', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 350', 'Mercedes-Benz GLS 350', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 400', 'Mercedes-Benz GLS 400', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 450', 'Mercedes-Benz GLS 450', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 500', 'Mercedes-Benz GLS 500', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 580', 'Mercedes-Benz GLS 580', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 600', 'Mercedes-Benz GLS 600', 'manual_mb'),
  ('Mercedes-Benz', 'GLS 63 AMG', 'Mercedes-Benz GLS 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GLS Maybach', 'Mercedes-Benz GLS Maybach', 'manual_mb'),
  ('Mercedes-Benz', 'GLK 200', 'Mercedes-Benz GLK 200', 'manual_mb'),
  ('Mercedes-Benz', 'GLK 220', 'Mercedes-Benz GLK 220', 'manual_mb'),
  ('Mercedes-Benz', 'GLK 250', 'Mercedes-Benz GLK 250', 'manual_mb'),
  ('Mercedes-Benz', 'GLK 280', 'Mercedes-Benz GLK 280', 'manual_mb'),
  ('Mercedes-Benz', 'GLK 320', 'Mercedes-Benz GLK 320', 'manual_mb'),
  ('Mercedes-Benz', 'GLK 350', 'Mercedes-Benz GLK 350', 'manual_mb'),
  ('Mercedes-Benz', 'G 320', 'Mercedes-Benz G 320', 'manual_mb'),
  ('Mercedes-Benz', 'G 350', 'Mercedes-Benz G 350', 'manual_mb'),
  ('Mercedes-Benz', 'G 400', 'Mercedes-Benz G 400', 'manual_mb'),
  ('Mercedes-Benz', 'G 500', 'Mercedes-Benz G 500', 'manual_mb'),
  ('Mercedes-Benz', 'G 550', 'Mercedes-Benz G 550', 'manual_mb'),
  ('Mercedes-Benz', 'G 55 AMG', 'Mercedes-Benz G 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'G 63 AMG', 'Mercedes-Benz G 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'G 65 AMG', 'Mercedes-Benz G 65 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'GL 320', 'Mercedes-Benz GL 320', 'manual_mb'),
  ('Mercedes-Benz', 'GL 350', 'Mercedes-Benz GL 350', 'manual_mb'),
  ('Mercedes-Benz', 'GL 420', 'Mercedes-Benz GL 420', 'manual_mb'),
  ('Mercedes-Benz', 'GL 450', 'Mercedes-Benz GL 450', 'manual_mb'),
  ('Mercedes-Benz', 'GL 500', 'Mercedes-Benz GL 500', 'manual_mb'),
  ('Mercedes-Benz', 'GL 550', 'Mercedes-Benz GL 550', 'manual_mb'),
  ('Mercedes-Benz', 'GL 63 AMG', 'Mercedes-Benz GL 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'ML 230', 'Mercedes-Benz ML 230', 'manual_mb'),
  ('Mercedes-Benz', 'ML 250', 'Mercedes-Benz ML 250', 'manual_mb'),
  ('Mercedes-Benz', 'ML 270', 'Mercedes-Benz ML 270', 'manual_mb'),
  ('Mercedes-Benz', 'ML 280', 'Mercedes-Benz ML 280', 'manual_mb'),
  ('Mercedes-Benz', 'ML 320', 'Mercedes-Benz ML 320', 'manual_mb'),
  ('Mercedes-Benz', 'ML 350', 'Mercedes-Benz ML 350', 'manual_mb'),
  ('Mercedes-Benz', 'ML 400', 'Mercedes-Benz ML 400', 'manual_mb'),
  ('Mercedes-Benz', 'ML 420', 'Mercedes-Benz ML 420', 'manual_mb'),
  ('Mercedes-Benz', 'ML 430', 'Mercedes-Benz ML 430', 'manual_mb'),
  ('Mercedes-Benz', 'ML 450', 'Mercedes-Benz ML 450', 'manual_mb'),
  ('Mercedes-Benz', 'ML 500', 'Mercedes-Benz ML 500', 'manual_mb'),
  ('Mercedes-Benz', 'ML 55 AMG', 'Mercedes-Benz ML 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'ML 63 AMG', 'Mercedes-Benz ML 63 AMG', 'manual_mb'),

  -- =========================================================================
  -- TRIMS SL / SLK / SLC
  -- =========================================================================
  ('Mercedes-Benz', 'SL 280', 'Mercedes-Benz SL 280', 'manual_mb'),
  ('Mercedes-Benz', 'SL 300', 'Mercedes-Benz SL 300', 'manual_mb'),
  ('Mercedes-Benz', 'SL 320', 'Mercedes-Benz SL 320', 'manual_mb'),
  ('Mercedes-Benz', 'SL 350', 'Mercedes-Benz SL 350', 'manual_mb'),
  ('Mercedes-Benz', 'SL 380', 'Mercedes-Benz SL 380', 'manual_mb'),
  ('Mercedes-Benz', 'SL 400', 'Mercedes-Benz SL 400', 'manual_mb'),
  ('Mercedes-Benz', 'SL 420', 'Mercedes-Benz SL 420', 'manual_mb'),
  ('Mercedes-Benz', 'SL 430', 'Mercedes-Benz SL 430', 'manual_mb'),
  ('Mercedes-Benz', 'SL 450', 'Mercedes-Benz SL 450', 'manual_mb'),
  ('Mercedes-Benz', 'SL 500', 'Mercedes-Benz SL 500', 'manual_mb'),
  ('Mercedes-Benz', 'SL 550', 'Mercedes-Benz SL 550', 'manual_mb'),
  ('Mercedes-Benz', 'SL 560', 'Mercedes-Benz SL 560', 'manual_mb'),
  ('Mercedes-Benz', 'SL 600', 'Mercedes-Benz SL 600', 'manual_mb'),
  ('Mercedes-Benz', 'SL 55 AMG', 'Mercedes-Benz SL 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SL 60 AMG', 'Mercedes-Benz SL 60 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SL 63 AMG', 'Mercedes-Benz SL 63 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SL 65 AMG', 'Mercedes-Benz SL 65 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SL 73 AMG', 'Mercedes-Benz SL 73 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 200', 'Mercedes-Benz SLK 200', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 230', 'Mercedes-Benz SLK 230', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 250', 'Mercedes-Benz SLK 250', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 280', 'Mercedes-Benz SLK 280', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 300', 'Mercedes-Benz SLK 300', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 320', 'Mercedes-Benz SLK 320', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 350', 'Mercedes-Benz SLK 350', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 32 AMG', 'Mercedes-Benz SLK 32 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SLK 55 AMG', 'Mercedes-Benz SLK 55 AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SLC 180', 'Mercedes-Benz SLC 180', 'manual_mb'),
  ('Mercedes-Benz', 'SLC 200', 'Mercedes-Benz SLC 200', 'manual_mb'),
  ('Mercedes-Benz', 'SLC 250', 'Mercedes-Benz SLC 250', 'manual_mb'),
  ('Mercedes-Benz', 'SLC 300', 'Mercedes-Benz SLC 300', 'manual_mb'),
  ('Mercedes-Benz', 'SLC 43 AMG', 'Mercedes-Benz SLC 43 AMG', 'manual_mb'),

  -- =========================================================================
  -- AMG GT / SLR / SLS / AMG ONE / SUPERCARS
  -- =========================================================================
  ('Mercedes-Benz', 'AMG GT', 'Mercedes-AMG GT', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT S', 'Mercedes-AMG GT S', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT C', 'Mercedes-AMG GT C', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT R', 'Mercedes-AMG GT R', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT R Pro', 'Mercedes-AMG GT R Pro', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT Black Series', 'Mercedes-AMG GT Black Series', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT 4-door', 'Mercedes-AMG GT 4-door', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT 43', 'Mercedes-AMG GT 43', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT 53', 'Mercedes-AMG GT 53', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT 63', 'Mercedes-AMG GT 63', 'manual_mb'),
  ('Mercedes-Benz', 'AMG GT 63 S', 'Mercedes-AMG GT 63 S', 'manual_mb'),
  ('Mercedes-Benz', 'AMG ONE', 'Mercedes-AMG ONE', 'manual_mb'),
  ('Mercedes-Benz', 'SLS AMG', 'Mercedes-Benz SLS AMG', 'manual_mb'),
  ('Mercedes-Benz', 'SLS AMG GT', 'Mercedes-Benz SLS AMG GT', 'manual_mb'),
  ('Mercedes-Benz', 'SLS AMG Black Series', 'Mercedes-Benz SLS AMG Black Series', 'manual_mb'),
  ('Mercedes-Benz', 'SLR McLaren', 'Mercedes-Benz SLR McLaren', 'manual_mb'),
  ('Mercedes-Benz', 'SLR Roadster', 'Mercedes-Benz SLR Roadster', 'manual_mb'),
  ('Mercedes-Benz', 'SLR 722', 'Mercedes-Benz SLR 722', 'manual_mb'),

  -- =========================================================================
  -- VINTAGES (collector premium)
  -- =========================================================================
  -- 190 (W201)
  ('Mercedes-Benz', '190', 'Mercedes-Benz 190', 'manual_mb'),
  ('Mercedes-Benz', '190 E', 'Mercedes-Benz 190 E', 'manual_mb'),
  ('Mercedes-Benz', '190 E 2.3-16', 'Mercedes-Benz 190 E 2.3-16', 'manual_mb'),
  ('Mercedes-Benz', '190 E 2.5-16', 'Mercedes-Benz 190 E 2.5-16', 'manual_mb'),
  ('Mercedes-Benz', '190 SL', 'Mercedes-Benz 190 SL', 'manual_mb'),
  ('Mercedes-Benz', '190 D', 'Mercedes-Benz 190 D', 'manual_mb'),
  -- W123 (200/240/250/280/300)
  ('Mercedes-Benz', '200 D', 'Mercedes-Benz 200 D', 'manual_mb'),
  ('Mercedes-Benz', '230 CE', 'Mercedes-Benz 230 CE', 'manual_mb'),
  ('Mercedes-Benz', '230 SL', 'Mercedes-Benz 230 SL', 'manual_mb'),
  ('Mercedes-Benz', '230 TE', 'Mercedes-Benz 230 TE', 'manual_mb'),
  ('Mercedes-Benz', '240 D', 'Mercedes-Benz 240 D', 'manual_mb'),
  ('Mercedes-Benz', '240 TD', 'Mercedes-Benz 240 TD', 'manual_mb'),
  ('Mercedes-Benz', '250 D', 'Mercedes-Benz 250 D', 'manual_mb'),
  ('Mercedes-Benz', '250 SL', 'Mercedes-Benz 250 SL', 'manual_mb'),
  ('Mercedes-Benz', '250 SE', 'Mercedes-Benz 250 SE', 'manual_mb'),
  ('Mercedes-Benz', '250 CE', 'Mercedes-Benz 250 CE', 'manual_mb'),
  ('Mercedes-Benz', '280 SL', 'Mercedes-Benz 280 SL', 'manual_mb'),
  ('Mercedes-Benz', '280 SE', 'Mercedes-Benz 280 SE', 'manual_mb'),
  ('Mercedes-Benz', '280 SEL', 'Mercedes-Benz 280 SEL', 'manual_mb'),
  ('Mercedes-Benz', '280 CE', 'Mercedes-Benz 280 CE', 'manual_mb'),
  ('Mercedes-Benz', '280 SLC', 'Mercedes-Benz 280 SLC', 'manual_mb'),
  ('Mercedes-Benz', '280 TE', 'Mercedes-Benz 280 TE', 'manual_mb'),
  -- 300 saga (W124, W126, R107, etc.)
  ('Mercedes-Benz', '300 SL', 'Mercedes-Benz 300 SL', 'manual_mb'),
  ('Mercedes-Benz', '300 SL Gullwing', 'Mercedes-Benz 300 SL Gullwing', 'manual_mb'),
  ('Mercedes-Benz', '300 SL Roadster', 'Mercedes-Benz 300 SL Roadster', 'manual_mb'),
  ('Mercedes-Benz', '300 SE', 'Mercedes-Benz 300 SE', 'manual_mb'),
  ('Mercedes-Benz', '300 SEL', 'Mercedes-Benz 300 SEL', 'manual_mb'),
  ('Mercedes-Benz', '300 SEL 6.3', 'Mercedes-Benz 300 SEL 6.3', 'manual_mb'),
  ('Mercedes-Benz', '300 SEC', 'Mercedes-Benz 300 SEC', 'manual_mb'),
  ('Mercedes-Benz', '300 D', 'Mercedes-Benz 300 D', 'manual_mb'),
  ('Mercedes-Benz', '300 SD', 'Mercedes-Benz 300 SD', 'manual_mb'),
  ('Mercedes-Benz', '300 SDL', 'Mercedes-Benz 300 SDL', 'manual_mb'),
  ('Mercedes-Benz', '300 E', 'Mercedes-Benz 300 E', 'manual_mb'),
  ('Mercedes-Benz', '300 CE', 'Mercedes-Benz 300 CE', 'manual_mb'),
  ('Mercedes-Benz', '300 TE', 'Mercedes-Benz 300 TE', 'manual_mb'),
  ('Mercedes-Benz', '300 TD', 'Mercedes-Benz 300 TD', 'manual_mb'),
  ('Mercedes-Benz', '300 SL-24', 'Mercedes-Benz 300 SL-24', 'manual_mb'),
  -- 320/350/380/400/420/450/500/560/600 saga
  ('Mercedes-Benz', '320 CE', 'Mercedes-Benz 320 CE', 'manual_mb'),
  ('Mercedes-Benz', '320 E', 'Mercedes-Benz 320 E', 'manual_mb'),
  ('Mercedes-Benz', '320 TE', 'Mercedes-Benz 320 TE', 'manual_mb'),
  ('Mercedes-Benz', '350 SL', 'Mercedes-Benz 350 SL', 'manual_mb'),
  ('Mercedes-Benz', '350 SLC', 'Mercedes-Benz 350 SLC', 'manual_mb'),
  ('Mercedes-Benz', '350 SE', 'Mercedes-Benz 350 SE', 'manual_mb'),
  ('Mercedes-Benz', '350 SEL', 'Mercedes-Benz 350 SEL', 'manual_mb'),
  ('Mercedes-Benz', '350 SEC', 'Mercedes-Benz 350 SEC', 'manual_mb'),
  ('Mercedes-Benz', '380 SL', 'Mercedes-Benz 380 SL', 'manual_mb'),
  ('Mercedes-Benz', '380 SLC', 'Mercedes-Benz 380 SLC', 'manual_mb'),
  ('Mercedes-Benz', '380 SE', 'Mercedes-Benz 380 SE', 'manual_mb'),
  ('Mercedes-Benz', '380 SEL', 'Mercedes-Benz 380 SEL', 'manual_mb'),
  ('Mercedes-Benz', '380 SEC', 'Mercedes-Benz 380 SEC', 'manual_mb'),
  ('Mercedes-Benz', '400 E', 'Mercedes-Benz 400 E', 'manual_mb'),
  ('Mercedes-Benz', '400 SE', 'Mercedes-Benz 400 SE', 'manual_mb'),
  ('Mercedes-Benz', '400 SEL', 'Mercedes-Benz 400 SEL', 'manual_mb'),
  ('Mercedes-Benz', '400 SEC', 'Mercedes-Benz 400 SEC', 'manual_mb'),
  ('Mercedes-Benz', '420 SE', 'Mercedes-Benz 420 SE', 'manual_mb'),
  ('Mercedes-Benz', '420 SEL', 'Mercedes-Benz 420 SEL', 'manual_mb'),
  ('Mercedes-Benz', '420 SEC', 'Mercedes-Benz 420 SEC', 'manual_mb'),
  ('Mercedes-Benz', '420 SL', 'Mercedes-Benz 420 SL', 'manual_mb'),
  ('Mercedes-Benz', '450 SL', 'Mercedes-Benz 450 SL', 'manual_mb'),
  ('Mercedes-Benz', '450 SLC', 'Mercedes-Benz 450 SLC', 'manual_mb'),
  ('Mercedes-Benz', '450 SE', 'Mercedes-Benz 450 SE', 'manual_mb'),
  ('Mercedes-Benz', '450 SEL', 'Mercedes-Benz 450 SEL', 'manual_mb'),
  ('Mercedes-Benz', '450 SEL 6.9', 'Mercedes-Benz 450 SEL 6.9', 'manual_mb'),
  ('Mercedes-Benz', '450 SEC', 'Mercedes-Benz 450 SEC', 'manual_mb'),
  ('Mercedes-Benz', '500 SL', 'Mercedes-Benz 500 SL', 'manual_mb'),
  ('Mercedes-Benz', '500 SLC', 'Mercedes-Benz 500 SLC', 'manual_mb'),
  ('Mercedes-Benz', '500 SE', 'Mercedes-Benz 500 SE', 'manual_mb'),
  ('Mercedes-Benz', '500 SEL', 'Mercedes-Benz 500 SEL', 'manual_mb'),
  ('Mercedes-Benz', '500 SEC', 'Mercedes-Benz 500 SEC', 'manual_mb'),
  ('Mercedes-Benz', '500 E', 'Mercedes-Benz 500 E', 'manual_mb'),
  ('Mercedes-Benz', '500 K', 'Mercedes-Benz 500 K', 'manual_mb'),
  ('Mercedes-Benz', '540 K', 'Mercedes-Benz 540 K', 'manual_mb'),
  ('Mercedes-Benz', '560 SL', 'Mercedes-Benz 560 SL', 'manual_mb'),
  ('Mercedes-Benz', '560 SE', 'Mercedes-Benz 560 SE', 'manual_mb'),
  ('Mercedes-Benz', '560 SEL', 'Mercedes-Benz 560 SEL', 'manual_mb'),
  ('Mercedes-Benz', '560 SEC', 'Mercedes-Benz 560 SEC', 'manual_mb'),
  ('Mercedes-Benz', '600', 'Mercedes-Benz 600', 'manual_mb'),
  ('Mercedes-Benz', '600 SE', 'Mercedes-Benz 600 SE', 'manual_mb'),
  ('Mercedes-Benz', '600 SEL', 'Mercedes-Benz 600 SEL', 'manual_mb'),
  ('Mercedes-Benz', '600 Pullman', 'Mercedes-Benz 600 Pullman', 'manual_mb'),
  ('Mercedes-Benz', '770', 'Mercedes-Benz 770', 'manual_mb'),
  ('Mercedes-Benz', 'SSK', 'Mercedes-Benz SSK', 'manual_mb'),
  -- Pagode/Heckflosse classics
  ('Mercedes-Benz', 'Pagode', 'Mercedes-Benz Pagode', 'manual_mb'),
  ('Mercedes-Benz', 'Adenauer', 'Mercedes-Benz Adenauer', 'manual_mb'),
  ('Mercedes-Benz', 'Heckflosse', 'Mercedes-Benz Heckflosse', 'manual_mb'),
  ('Mercedes-Benz', 'Ponton', 'Mercedes-Benz Ponton', 'manual_mb'),
  ('Mercedes-Benz', 'Gullwing', 'Mercedes-Benz Gullwing', 'manual_mb')

ON CONFLICT (mk, mo) DO NOTHING;

-- Cleanup pollutions Mercedes-Benz Wikipedia (camions/buses)
DELETE FROM public.models_canonical
WHERE mk = 'Mercedes-Benz' AND source = 'wikipedia_cat'
  AND (
    mo ILIKE '%actros%' OR mo ILIKE '%atego%' OR mo ILIKE '%arocs%'
    OR mo ILIKE '%axor%' OR mo ILIKE '%antos%' OR mo ILIKE '%econic%'
    OR mo ILIKE '%zetros%' OR mo ILIKE '%unimog%'
    OR mo ILIKE '%citaro%' OR mo ILIKE '%tourismo%' OR mo ILIKE '%travego%'
    OR mo ILIKE '%intouro%' OR mo ILIKE '%conecto%'
  );

-- Vérification counts Mercedes-Benz par source
SELECT source, COUNT(*) AS n
FROM public.models_canonical
WHERE mk = 'Mercedes-Benz'
GROUP BY source
ORDER BY n DESC;
