"""Generate test fixtures for extract_features_v2 from real DB descriptions.

Selects 4 representative descriptions covering the main formats observed
in the live dataset (Mai 2026) and writes them as .txt files in
tests/fixtures/. Run once at the start of Mission extract_features v2
(étape 1) and again whenever fixture IDs change.

Each fixture is an actual `de` value from the DB, prefixed with a
metadata header. Re-running this script overwrites existing fixtures —
keep FIXTURES IDs stable so re-runs are deterministic.

The IT fixture is not generated yet — no Italian source is currently
connected. Will be added once Mobile.de or another DACH+IT source is
unblocked.

Usage:
    python scripts/generate_v2_fixtures.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
load_dotenv(ROOT / '.env')


# (filename, car_id, format_label)
FIXTURES = [
    (
        'extract_v2_nl_options.txt',
        'a60060b1-becd-4dac-925d-165309867ca0',
        'NL — fiche technique structurée + équipements (AutoScout24 Belgique, Skoda Octavia SW)',
    ),
    (
        'extract_v2_fr_editorial.txt',
        'cc12dc9c-220c-4c88-aa2a-ea2fcf5459d3',
        "FR éditorial — Points forts + L'Attrait (LesAnciennes, Alpina B5 Biturbo)",
    ),
    (
        'extract_v2_fr_commercial.txt',
        'd34f2b0d-1265-4131-b270-d650968deb6e',
        "FR commercial — catalogue d'options par section (Auto Selection, Alfa Giulietta)",
    ),
    (
        'extract_v2_multilang_be.txt',
        '704d219e-df60-4d5f-a188-78f098b2882c',
        'Multi-langue — sections NL/FR/DE par drapeau dans la même description (AutoScout24 Belgique, Mercedes-Benz)',
    ),
]


def main() -> int:
    sb = create_client(os.environ['SUPABASE_URL'], os.environ['SUPABASE_SERVICE_KEY'])

    fixtures_dir = ROOT / 'tests' / 'fixtures'
    fixtures_dir.mkdir(parents=True, exist_ok=True)

    print(f'Generating fixtures in {fixtures_dir}')

    written = 0
    skipped = 0

    for filename, car_id, label in FIXTURES:
        try:
            row = (sb.table('cars')
                   .select('id, mk, mo, src, co, de')
                   .eq('id', car_id)
                   .single()
                   .execute()
                   .data)
        except Exception as e:
            print(f'  ✗ {filename}: query error for {car_id}: {e}')
            skipped += 1
            continue

        if not row:
            print(f'  ✗ {filename}: car id {car_id} not found in DB')
            skipped += 1
            continue

        de = row.get('de') or ''
        if not de:
            print(f'  ✗ {filename}: car {car_id} has empty de')
            skipped += 1
            continue

        header = (
            f'# Fixture: {label}\n'
            f'# Source: {row["src"]} ({row["co"]})\n'
            f'# Vehicle: {row["mk"]} {row["mo"]}\n'
            f'# id: {row["id"]}\n'
            f'# de length: {len(de)} chars\n'
            f'# Generated by scripts/generate_v2_fixtures.py — DO NOT EDIT MANUALLY\n'
            f'# (Re-run the script to refresh from DB)\n'
            '\n'
        )

        out_path = fixtures_dir / filename
        out_path.write_text(header + de, encoding='utf-8')
        print(f'  ✓ {filename} ({len(de)} chars)')
        written += 1

    print(f'\nDone. Written: {written} | Skipped: {skipped} | Total: {len(FIXTURES)}')
    return 0 if skipped == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
