    # ═══════════════════════════════════════════════════════════════════════
    # PHASE A — VAGUE 2 (mai 2026)
    # 30 dealers : 12 Monaco + 8 Andorre + 6 France + 1 Allemagne + 3 mono-marque officiels
    # listings_url / sitemap_url / domain / base_url / lat / lng a remplir au sniff
    # ═══════════════════════════════════════════════════════════════════════

    # ─────── Vague 2 — Monaco (12 dealers, tier 1) ──────────────────────────

    "exclusive-cars-monaco": {
        "slug": "exclusive-cars-monaco",
        "display_name": "Exclusive Cars Monaco",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Premium occasion luxe Monaco",
        "brand_focus": [],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2. Site web a confirmer au sniff.",
    },

    "dpm-motors": {
        "slug": "dpm-motors",
        "display_name": "DPM Motors",
        "domain": "dpm-motors.com",
        "base_url": "https://www.dpm-motors.com",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Specialiste vehicules occasion luxe Monaco",
        "brand_focus": [],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2. dpm-motors.com confirme. Pilote sniff Monaco.",
    },

    "bpm-exclusive": {
        "slug": "bpm-exclusive",
        "display_name": "BPM Exclusive",
        "domain": "bpmexclusive.com",
        "base_url": "https://bpmexclusive.com",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Multi-marques prestige Monaco",
        "brand_focus": ["Ferrari", "Maserati", "Bentley", "Mercedes", "Aston Martin"],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2. bpmexclusive.com. Inclut Aston Martin Monaco.",
    },

    "rs-monaco": {
        "slug": "rs-monaco",
        "display_name": "RS Monaco",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Ferrari et supercars Monaco",
        "brand_focus": ["Ferrari"],
        "estimated_stock": 20,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "groupe-segond": {
        "slug": "groupe-segond",
        "display_name": "Groupe Segond Automobiles",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Concession multi-marques Monaco",
        "brand_focus": [],
        "estimated_stock": 25,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "monaco-motors": {
        "slug": "monaco-motors",
        "display_name": "Monaco Motors",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Concession Monaco",
        "brand_focus": [],
        "estimated_stock": 15,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "monaco-supercars": {
        "slug": "monaco-supercars",
        "display_name": "Monaco Supercars",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Supercars Monaco",
        "brand_focus": [],
        "estimated_stock": 10,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "monaco-infinity-luxury": {
        "slug": "monaco-infinity-luxury",
        "display_name": "Monaco Infinity Luxury",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Luxe occasion Monaco",
        "brand_focus": [],
        "estimated_stock": 15,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "gabriel-cavallari": {
        "slug": "gabriel-cavallari",
        "display_name": "Gabriel Cavallari",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Concession Monaco — Cote d'Azur",
        "brand_focus": [],
        "estimated_stock": 15,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2. A verifier au sniff : possible doublon Groupe Cavallari (cavallari.fr) qui couvre Nice/Cannes/Monaco/Menton.",
    },

    "mz-motors-monaco": {
        "slug": "mz-motors-monaco",
        "display_name": "MZ Motors Monaco",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Concession Monaco",
        "brand_focus": [],
        "estimated_stock": 10,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "car-legendary-monaco": {
        "slug": "car-legendary-monaco",
        "display_name": "Car Legendary Monaco",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Concession Monaco 24h/24",
        "brand_focus": [],
        "estimated_stock": 10,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "monaco-occasions": {
        "slug": "monaco-occasions",
        "display_name": "Monaco-Occasions",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Occasion Fontvieille Monaco",
        "brand_focus": [],
        "estimated_stock": 25,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    # ─────── Vague 2 — Andorre (8 dealers, tier 1-2) ────────────────────────
    # Note : language=ca / timezone=Europe/Andorra cote DB

    "exotic-cars-andorre": {
        "slug": "exotic-cars-andorre",
        "display_name": "Exotic Cars Andorre",
        "country": "Andorre", "city": "Erts",
        "tier": 1, "type": "dealer",
        "specialty": "Specialiste exotiques et supercars Andorre",
        "brand_focus": [],
        "estimated_stock": 15,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2. Promu tier 1 pour specialisation exotiques.",
    },

    "seuwagen": {
        "slug": "seuwagen",
        "display_name": "SEUWAGEN",
        "country": "Andorre", "city": "Andorra la Vella",
        "tier": 2, "type": "dealer",
        "specialty": "Concession volume Andorre",
        "brand_focus": [],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "centre-prestigi-automobils": {
        "slug": "centre-prestigi-automobils",
        "display_name": "Centre Prestigi Automobils",
        "country": "Andorre", "city": "Les Escaldes",
        "tier": 2, "type": "dealer",
        "specialty": "Concession multi-marques Andorre",
        "brand_focus": [],
        "estimated_stock": 20,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "ted-automobil-andorra": {
        "slug": "ted-automobil-andorra",
        "display_name": "Ted Automobil Andorra",
        "country": "Andorre", "city": "Encamp",
        "tier": 2, "type": "dealer",
        "specialty": "Concession Andorre",
        "brand_focus": [],
        "estimated_stock": 25,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "cotxes-ml-automobils": {
        "slug": "cotxes-ml-automobils",
        "display_name": "Cotxes M.L. Automobils",
        "country": "Andorre", "city": "La Massana",
        "tier": 2, "type": "dealer",
        "specialty": "Concession Andorre note 5/5",
        "brand_focus": [],
        "estimated_stock": 20,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "ballestas-automocio": {
        "slug": "ballestas-automocio",
        "display_name": "Ballestas Automocio",
        "country": "Andorre", "city": "Andorra la Vella",
        "tier": 2, "type": "dealer",
        "specialty": "Concession Andorre",
        "brand_focus": [],
        "estimated_stock": 20,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "r1-collection": {
        "slug": "r1-collection",
        "display_name": "R1 Collection",
        "country": "Andorre", "city": "Encamp",
        "tier": 2, "type": "dealer",
        "specialty": "Concession Andorre note 5/5",
        "brand_focus": [],
        "estimated_stock": 15,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "kars-automobils": {
        "slug": "kars-automobils",
        "display_name": "KARS Automobils",
        "country": "Andorre", "city": "Andorra la Vella",
        "tier": 2, "type": "dealer",
        "specialty": "Concession Andorre",
        "brand_focus": [],
        "estimated_stock": 15,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    # ─────── Vague 2 — France (6 specialistes, tier 1-2) ────────────────────

    "gtcars-prestige": {
        "slug": "gtcars-prestige",
        "display_name": "GTcars Prestige",
        "country": "France", "city": "Sainte-Genevieve-des-Bois",
        "tier": 1, "type": "dealer",
        "specialty": "Courtier supercars (Bugatti, Pagani, Koenigsegg)",
        "brand_focus": ["Bugatti", "Pagani", "Koenigsegg"],
        "estimated_stock": 10,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2. Bugatti visible sur photo GMaps. Stock probablement faible mais ultra-premium.",
    },

    "luxury-performance-selection": {
        "slug": "luxury-performance-selection",
        "display_name": "Luxury & Performance Selection",
        "country": "France", "city": "Antibes",
        "tier": 1, "type": "dealer",
        "specialty": "Prestige Cote d'Azur",
        "brand_focus": [],
        "estimated_stock": 25,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "bourcier-auto-sport": {
        "slug": "bourcier-auto-sport",
        "display_name": "Bourcier Auto Sport",
        "country": "France", "city": "Saint-Barthelemy-d'Anjou",
        "tier": 2, "type": "dealer",
        "specialty": "Specialiste Porsche, prestige et classics — 25 ans",
        "brand_focus": ["Porsche"],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "code-911": {
        "slug": "code-911",
        "display_name": "Code 911 Sport & Prestige",
        "country": "France", "city": "La Chapelle-des-Fougeretz",
        "tier": 2, "type": "dealer",
        "specialty": "Specialiste Porsche Bretagne",
        "brand_focus": ["Porsche"],
        "estimated_stock": 20,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "orleans-cars-shop": {
        "slug": "orleans-cars-shop",
        "display_name": "Orleans Cars Shop",
        "country": "France", "city": "Ingre",
        "tier": 2, "type": "dealer",
        "specialty": "Vehicules de prestige et sportifs",
        "brand_focus": [],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    "passion-automobiles-prestige-bentley": {
        "slug": "passion-automobiles-prestige-bentley",
        "display_name": "Passion Automobiles Prestige — Bentley Service",
        "country": "France", "city": "Sausheim",
        "tier": 2, "type": "dealer",
        "specialty": "Specialiste Bentley Service Alsace",
        "brand_focus": ["Bentley"],
        "estimated_stock": 10,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2.",
    },

    # ─────── Vague 2 — Allemagne (1 pilote DE-Sud, tier 2) ──────────────────
    # Note : language=de / timezone=Europe/Berlin cote DB

    "autohaus-prestige-selections": {
        "slug": "autohaus-prestige-selections",
        "display_name": "Autohaus Prestige Selections",
        "country": "Allemagne", "city": "Freiburg im Breisgau",
        "tier": 2, "type": "dealer",
        "specialty": "Concession premium occasion DE-Sud",
        "brand_focus": [],
        "estimated_stock": 30,
        "scrape_method": "httpx_bs4",
        "score_bonus": 3,
        "selectors": {},
        "notes": "Vague 2 — pilote DE. Premiere source allemande, valider format JSON-LD allemand au sniff. Make_normalizer.py probablement a etendre.",
    },

    # ─────── Vague 2 — Mono-marque officiels exotiques (3 dealers, tier 1) ──
    # Pitch partenariat prepare (cf docs/partnerships_pitch_concessions_officielles.md)
    # Envoi au seuil >=5k MAU + >=50k listings + page /methode + ONG

    "lamborghini-porrentruy": {
        "slug": "lamborghini-porrentruy",
        "display_name": "Lamborghini Porrentruy",
        "country": "Suisse", "city": "Porrentruy",
        "tier": 1, "type": "dealer",
        "specialty": "Concession officielle Lamborghini Suisse romande — Jura/Arc jurassien",
        "brand_focus": ["Lamborghini"],
        "estimated_stock": 8,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2 — mono-marque officiel. Pitch partenariat prepare, envoi au seuil traffic. Currency=CHF / timezone=Europe/Zurich cote DB.",
    },

    "mclaren-monaco": {
        "slug": "mclaren-monaco",
        "display_name": "McLaren Monaco",
        "country": "Monaco", "city": "Monaco",
        "tier": 1, "type": "dealer",
        "specialty": "Concession officielle McLaren Monaco",
        "brand_focus": ["McLaren"],
        "estimated_stock": 6,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2 — mono-marque officiel. Pitch partenariat prepare, envoi au seuil traffic.",
    },

    "centre-porsche-geneve": {
        "slug": "centre-porsche-geneve",
        "display_name": "Centre Porsche Geneve",
        "country": "Suisse", "city": "Le Grand-Saconnex",
        "tier": 1, "type": "dealer",
        "specialty": "Concession officielle Porsche Geneve",
        "brand_focus": ["Porsche"],
        "estimated_stock": 40,
        "scrape_method": "httpx_bs4",
        "score_bonus": 5,
        "selectors": {},
        "notes": "Vague 2 — mono-marque officiel. Pitch partenariat prepare, envoi au seuil traffic. Currency=CHF / timezone=Europe/Zurich cote DB.",
    },
